const TEAMS_CONVERTION = {
  ORL: "Orlando Magic",
  OKC: "Oklahoma City Thunder",
  LAL: "Los Angeles Lakers",
  IND: "Indiana Pacers",
  ATL: "Atlanta Hawks",
  SA: "San Antonio Spurs",
  SAC: "Sacramento Kings",
  GS: "Golden State Warriors",
  MEM: "Memphis Grizzlies",
  MIA: "Miami Heat",
  PHI: "Philadelphia 76ers",
  CHA: "Charlotte Hornets",
  NO: "New Orleans Pelicans",
  DET: "Detroit Pistons",
  LAC: "LA Clippers",
  CLE: "Cleveland Cavaliers",
  DEN: "Denver Nuggets",
  PHX: "Phoenix Suns",
  NY: "New York Knicks",
  WSH: "Washington Wizards",
  BKN: "Brooklyn Nets",
  BOS: "Boston Celtics",
  MIL: "Milwaukee Bucks",
  POR: "Portland Trail Blazers",
  HOU: "Houston Rockets",
  MIN: "Minnesota Timberwolves",
  DAL: "Dallas Mavericks",
  UTA: "Utah Jazz",
  TOR: "Toronto Raptors",
  CHI: "Chicago Bulls",
};

const TEAMS_IMGS = {
  ORL: "Orlando Magic",
  OKC: "Oklahoma City Thunder",
  LAL: "Los Angeles Lakers",
  IND: "Indiana Pacers",
  ATL: "Atlanta Hawks",
  SA: "San Antonio Spurs",
  SAC: "Sacramento Kings",
  GS: "Golden State Warriors",
  MEM: "Memphis Grizzlies",
  MIA: "Miami Heat",
  PHI: "Philadelphia 76ers",
  CHA: "Charlotte Hornets",
  NO: "New Orleans Pelicans",
  DET: "Detroit Pistons",
  LAC: "LA Clippers",
  CLE: "Cleveland Cavaliers",
  DEN: "Denver Nuggets",
  PHX: "Phoenix Suns",
  NY: "New York Knicks",
  WSH: "Washington Wizards",
  BKN: "Brooklyn Nets",
  BOS: "Boston Celtics",
  MIL: "Milwaukee Bucks",
  POR: "Portland Trail Blazers",
  HOU: "Houston Rockets",
  MIN: "Minnesota Timberwolves",
  DAL: "Dallas Mavericks",
  UTA: "Utah Jazz",
  TOR: "Toronto Raptors",
  CHI: "Chicago Bulls",
};

export default TEAMS_CONVERTION;
